void bubble_sort (int vetor[], int n);
void insert_sort(int vetor[], int n);
void selection_sort(int vetor[], int n);
void shell_sort(int vetor[], int n);
void merge(int *vetor, int ini, int meio, int fim);
void merge_sort(int *vetor, int ini, int fim);
int quick(int *vetor, int ini, int fim);
void quick_sort(int *vetor, int ini, int fim);
void heap_sort(int *vet, int n);
void heap(int *vet, int raiz, int fundo);